### ISSUE TITLE
Cross-hair doesn't invert colours

### ISSUE THREAD

**Issue by Purrrpley** [ruvaldak/Semitranslucency#4]
In vanilla, the cross-hair isn't rendered just as texture specified in `assets/minecraft/textures/gui/icons.png`, it's actually used as a mask to invert colours (which allows you to see it whether you're looking at something dark or something bright). Because this mod makes the cross-hair (it's a HUD element) render as a texture with transparency, that colour inversion feature seems to be broken.

Ideally it should use the transparency level to figure out how much it should invert the colours by (like overlay the inverted colour with however much transparency was specified by the pixel). Making it just not affect the cross-hair at all though would probably be easier and still fine for most use-cases (like mine, I just want this so I can have partially transparent inventories).

Vanilla:
![image](https://user-images.githubusercontent.com/63091454/190020390-eb65b71d-c0bc-4c19-8401-369200f236e8.png)
With semi-translucency fix:
![image](https://user-images.githubusercontent.com/63091454/190020847-589bd692-efba-4e1c-a4ae-4f25b71a8e7b.png)
With semi-translucency fix (and a resource pack making the cross-hair 50% transparent, so you can see that the transparency does work):
![image](https://user-images.githubusercontent.com/63091454/190020781-a8a8dcdc-71dd-40ea-9cf6-181d5c525171.png)

(tested in 1.19.2 using Quilt and mod version [1.1-fabric](https://modrinth.com/mod/semitranslucency/version/1.1-fabric), in-case that matters)

**Comment by ruvaldak** [comment]
Huh. Weird. Didn't know that this caused that, but now that you point it out, yeah, I've noticed that.

I'm not sure if I can fix that, or if I even have the knowledge to.

**Comment by ruvaldak** [comment]
fixed with 2d06db763d24c50bd49dec2fbad2c4270bef9dad
