### ISSUE TITLE
Grindstone GUI renders twice

### ISSUE THREAD

**Issue by Mosscairn** [ruvaldak/Semitranslucency#5]
![image](https://user-images.githubusercontent.com/54695659/193698279-5bb33fd7-f5a0-49b6-86d1-92351d7dcfaa.png)
![image](https://user-images.githubusercontent.com/54695659/193698290-a9801476-4a7e-4ec8-9ef1-20b38c56909b.png)
Hello, i'm on fabric 1.19.2 and it appears that the grindstone interface renders twice?
it's possible this could be an issue with vanilla that just wasn't noticed because translucency wasn't supported? but i'm not entirely sure

**Comment by ruvaldak** [comment]
Definitely possible, but double check other mods aren't causing it please

**Comment by ruvaldak** [comment]
I can't recreate this issue.
