### ISSUE TITLE
Vignette transparency breaks when blending is enabled (1.19.4 only)

### ISSUE THREAD

**Issue by Nolij** [ruvaldak/Semitranslucency#7]
![image](https://user-images.githubusercontent.com/16640162/228661214-7648e087-49b2-48a4-8cae-965694375dc6.png)

I have tested with all other mods disabled.

**Comment by ruvaldak** [comment]
Weird that this is occuring only now, and hadn't been reported until now. I suspect something else is causing it. Or perhaps 1.19.4 changed something this mod relied on

**Comment by Nolij** [comment]
> 

I believe it is 1.19.4 that caused this problem, yes. The same modlist worked fine in 1.19.3.

**Comment by ruvaldak** [comment]
Ugh. Why's Mojang gotta break everything all the damn time

**Comment by ruvaldak** [comment]
The world does render, however Mojank did something to the default vignette that causes it's transparency to break when we turn blending on. That's why you see the white vignette around the edges of the screen, but the rest is black.

**Comment by ruvaldak** [comment]
although be915383abae2924cef061648daa8904ce45f604 says it fixes this, it does not.
