### ISSUE TITLE
Issue loading on quilt

### ISSUE THREAD

**Issue by cootshk** [ruvaldak/Semitranslucency#8]
crash report: https://mclo.gs/fT78JLh

**Comment by ruvaldak** [comment]
Meh.. I can barely keep up with fabric support, let alone the completely dead forge version.. supporting yet another modloader sounds like a nightmare. Wonder why quilt crashes though, it's supposed to support fabric mods.

Edit: looks like it hates my mixin for some reason, but I can't tell why. Does this happen with only quilt and semi-translucency?

**Comment by ruvaldak** [comment]
fixed in the latest release, 2.0.0-beta
